/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee_project;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frmSessionUser extends javax.swing.JFrame {
    private Connection con=null;
    private DefaultTableModel tM= new DefaultTableModel();
    private JTable tblData= new JTable();
/**
     * Creates new form frmSession
     */
    //Tao ban
    public frmSessionUser() {
          JLabel ten= new JLabel("Số Hóa Đơn: ");
        ten.setFont(new Font("Time New Roman", Font.BOLD, 14));
        JTextField sHD= new JTextField();
       String [] colName = {"Mã Số", "Tên Hàng", "Đơn Vi Tính", "Loại", "Giá"};
       tM.setColumnIdentifiers(colName); //dat ten cot cho tM
       tblData.setModel(tM); //ket noi tblData vs tM
       init();
       connect(); //ket noi vs CSDL
       updateData(view()); //goi ham view de truy xuat du lieu sau do truyen cho ham update
    }
    public void updateData(ResultSet rs){
        String [] colName = {"Mã Số", "Tên Hàng", "Đơn Vi Tính", "Loại", "Giá"};
        tM.setColumnIdentifiers(colName);
        try{
            while (rs.next()){//neu con doc tiep duoc 1 dong du lieu
                String rows[]=new String[5];
                rows[0]= rs.getString(1);//llay du lieu tai cot so 1
                rows[1]=rs.getString(2);
                rows[2]=rs.getString(3);
                rows[3]=rs.getString(4);
                rows[4]=rs.getString(5);
                tM.addRow(rows);//dua dong dulieu vao TM de hien thi len TB
                //moi lan co su thay doi dl o tM thi Tb se dc update lai
            }
        }catch (SQLException e){
                    e.printStackTrace();
             }
    }
    public void init(){
        JLabel ten= new JLabel("Số Hóa Đơn: ");
        ten.setFont(new Font("Time New Roman", Font.BOLD, 14));
        JTextField sHD= new JTextField();
        this.setSize(800, 400);
        //Dua TB vao thanh cuon
        JScrollPane scr= JTable.createScrollPaneForTable(tblData);
        this.add(scr); //dua thanh cuon vao frame
        this.add(ten);
        this.add(sHD);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }
    public void connect(){
        try{
             String bdUrl= "jdbc:sqlserver://LAPTOP-QC706BJT:1433; databaseName= Cf; user=sa;password=vinh1720";
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             try{
                 con= DriverManager.getConnection(bdUrl);
             } catch (SQLException ex) {
                        ex.printStackTrace();
            }
        } catch (ClassNotFoundException ex) {
                      ex.printStackTrace();
        }
    }
    public ResultSet view(){
        ResultSet rs=null;
        String sql = "Select * from sanpham";
        try{
            Statement st = (Statement) con.createStatement();
            return st.executeQuery(sql);
        }catch(SQLException e){
            e.printStackTrace();
        }
        return rs;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("SỐ HÓA ĐƠN");

        jTextField1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(531, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(539, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSessionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSessionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSessionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSessionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSessionUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
